### PR TITLE
Changed the sound.

### PR DESCRIPTION
**Pull request by gokabou**
I changed the sound to bell.mp3 and modify the code in public/script.js which is related to the sound source.

### CODE REVIEW

**Comment by esnya** [comment]
It will works. But `public/script.js` is an auto-generated file.
So you should not modify this file.

Then I removed `public/script.js` from the repository.
Please pull my master branch and modify original source files in `jsx/`

And you should also do followings:
- Read TOS of `bell.mp3` and modify `README.md`.
- Remove old unused sound file.

Thank you

**Comment by gokabou** [comment]
I've pulled your master branch.

And I have a question.

> Read TOS of bell.mp3 and modify README.md.

Does the "TOS" mean "type of service"?

**Comment by esnya** [comment]
"TOS" means "Terms of service".

**Comment by gokabou** [comment]
I see.

Thanks.

**Pull request closed without merging**
