### PR TITLE
Modified README.md and the sound

### PR DESCRIPTION
**Pull request by gokabou**
I modified README.md.
- fixed some typo
- added the web site name and its URL where I download the sound in Thanks
- added the caution according to the web site

### CODE REVIEW

**Comment by esnya** [comment]
`bell.mp3` should be placed in `public/`.

**Comment by gokabou** [comment]
I've moved it.

**Comment by esnya** [comment]
Merged
Good work :+1:

**Comment by gokabou** [comment]
Thanks for your great help :-)

**Pull request merged**
